
export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAILURE = 'OTP_FAILURE';

export const SET_TRIP_DETAILS = 'SET_TRIP_DETAILS';

export const TRIP_REQUEST = 'TRIP_REQUEST';
export const TRIP_SUCCESS = 'TRIP_SUCCESS';
export const TRIP_FAILURE = 'TRIP_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNUPRESPONSE_REQUEST = 'SIGNUPRESPONSE_REQUEST';
export const SIGNUPRESPONSE_SUCCESS = 'SIGNUPRESPONSE_SUCCESS';
export const SIGNUPRESPONSE_FAILURE = 'SIGNUPRESPONSE_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SET_PASSENGER_COUNT = 'SET_PASSENGER_COUNT';