
export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAILURE = 'OTP_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNUPRESPONSE_REQUEST = 'SIGNUPRESPONSE_REQUEST';
export const SIGNUPRESPONSE_SUCCESS = 'SIGNUPRESPONSE_SUCCESS';
export const SIGNUPRESPONSE_FAILURE = 'SIGNUPRESPONSE_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGINRESPONSE_SUCCESS = 'LOGINRESPONSE_SUCCESS';
export const LOGINRESPONSE_FAILURE = 'LOGINRESPONSE_FAILURE';

export const NOTESRESPONSE_REQUEST = 'NOTESRESPONSE_REQUEST';
export const NOTESRESPONSE_SUCCESS = 'NOTESRESPONSE_SUCCESS';
export const NOTESRESPONSE_FAILURE = 'NOTESRESPONSE_FAILURE';
